<?php
/************************************************************/
/*	BrilliantRetail 										*/
/*															*/
/*	@package	BrilliantRetail								*/
/*	@Author		David Dexter  								*/
/* 	@copyright	Copyright (c) 2010-2012						*/
/* 	@license	http://brilliantretail.com/license.html		*/
/* 	@link		http://brilliantretail.com 					*/
/* 	@since		Version 1.0.0 Beta							*/
/*															*/
/************************************************************/
/* NOTICE													*/
/*															*/
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF 	*/
/* ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED	*/
/* TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 		*/
/* PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT 		*/
/* SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION	*/
/* OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR 	*/
/* IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 		*/
/* DEALINGS IN THE SOFTWARE. 								*/	
/************************************************************/

/*
$this->load->dbforge();

for($i=1;$i<=6;$i++){
	$this->dbforge->add_column('channel_data', array(
													'field_id_'.$i => array(
																				'type' => 'TEXT', 
							    	                                        	'null' => TRUE 
							        	                                    )));
	$this->dbforge->add_column('channel_data', array(
													'field_ft_'.$i => array(
																				'type' => 'TINYTEXT', 
							    	                                           	'null' => TRUE 
							        	                        			)));
}

 
## exp_channel_data

	$sql[] = "INSERT INTO exp_channel_data 
(entry_id, site_id, channel_id, field_id_1, field_ft_1, field_id_2, field_ft_2, field_id_3, field_ft_3, field_id_4, field_ft_4, field_id_5, field_ft_5, field_id_6, field_ft_6) 
VALUES
(1, 1, 1, '', 'xhtml', '', 'xhtml', '', 'xhtml', '', 'xhtml', '', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml'),
(2, 1, 1, '', 'xhtml', '', 'xhtml', '', 'xhtml', '', 'xhtml', '', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml'),
(3, 1, 1, '', 'xhtml', '', 'xhtml', '', 'xhtml', '', 'xhtml', '', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml'),
(4, 1, 1, '', 'xhtml', '', 'xhtml', '', 'xhtml', '', 'xhtml', '', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml'),
(6, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(7, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(8, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(9, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(10, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(11, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(12, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(13, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(14, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(15, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(16, 1, 2, '', NULL, '{filedir_1}sample01.jpg', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', 'Liponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.\n\nLiponsectetur adipiscing elit. Duis elit ipsum, cursus a sollicitudin nec, fermentum vitae nibh. In a metus id leo mattis Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis mi leo. Quisque diam felis, vestibulum ut commodo a, mollis ac sem. Donec quis augue id neque auctor tincidunt eu eget mauris. Donec et risus elit, ac sagittis nibh.at tellus, a bibendum tortor lectus et mi.', 'xhtml', '2527', 'xhtml', '', 'xhtml'),
(17, 1, 3, '2527,2523,2522,2508', NULL, '', NULL, '', NULL, '', NULL, '', NULL, '', 'xhtml')";
	
## exp_channel_fields

	$sql[] = "	INSERT INTO 
					exp_channel_fields 
				VALUES 
						('1', '1', '3', 'best_sellers', 'Best Sellers', '', 'brilliant_retail', '', '0', '0', '0', 'channel', '2', 'title', 'desc', '0', '6', '128', 'n', 'ltr', 'n', 'n', 'xhtml', 'n', '1', 'any', 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30='), 
						('2', '1', '2', 'blog_img', 'Image', '', 'file', '', '0', '0', '0', 'channel', '2', 'title', 'desc', '0', '6', '128', 'n', 'ltr', 'n', 'n', 'xhtml', 'n', '1', 'any', 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30='), 
						('3', '1', '2', 'blog_summary', 'Summary', '', 'textarea', '', '0', '0', '0', 'channel', '2', 'title', 'desc', '0', '6', '128', 'n', 'ltr', 'n', 'n', 'xhtml', 'n', '2', 'any', 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30='), 
						('4', '1', '2', 'blog_content', 'Content', '', 'textarea', '', '0', '0', '0', 'channel', '2', 'title', 'desc', '0', '6', '128', 'n', 'ltr', 'n', 'n', 'xhtml', 'n', '3', 'any', 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30='), 
						('5', '1', '2', 'blog_products', 'Products', '', 'brilliant_retail', '', '0', '0', '0', 'channel', '2', 'title', 'desc', '0', '6', '128', 'n', 'ltr', 'n', 'n', 'xhtml', 'n', '4', 'any', 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToibiI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToibiI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6Im4iO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6Im4iO30='), 
						('6', '1', '1', 'general-content', 'General Content', '', 'textarea', '', '0', '0', '0', 'channel', '2', 'title', 'desc', '0', '6', '128', 'n', 'ltr', 'n', 'n', 'xhtml', 'n', '1', 'any', 'YTo2OntzOjE4OiJmaWVsZF9zaG93X3NtaWxleXMiO3M6MToibiI7czoxOToiZmllbGRfc2hvd19nbG9zc2FyeSI7czoxOiJuIjtzOjIxOiJmaWVsZF9zaG93X3NwZWxsY2hlY2siO3M6MToieSI7czoyNjoiZmllbGRfc2hvd19mb3JtYXR0aW5nX2J0bnMiO3M6MToieSI7czoyNDoiZmllbGRfc2hvd19maWxlX3NlbGVjdG9yIjtzOjE6InkiO3M6MjA6ImZpZWxkX3Nob3dfd3JpdGVtb2RlIjtzOjE6InkiO30=')";
	*/
	
## exp_field_groups

	$sql[] = "INSERT INTO exp_field_groups VALUES 
				('1', '1', 'General Content'), 
				('2', '1', 'Blog Fields'), 
				('3', '1', 'Home Page');";

## exp_field_formatting
	
	$sql[] = "INSERT INTO exp_field_formatting VALUES 
				('1', '1', 'xhtml'), 
				('2', '1', 'br'), 
				('3', '1', 'none'), 
				('4', '2', 'none'), 
				('5', '2', 'br'), 
				('6', '2', 'xhtml'), 
				('7', '3', 'none'), 
				('8', '3', 'br'), 
				('9', '3', 'xhtml'), 
				('10', '4', 'none'), 
				('11', '4', 'br'), 
				('12', '4', 'xhtml'), 
				('13', '5', 'none'), 
				('14', '5', 'br'), 
				('15', '5', 'xhtml'),
				('16', '6', 'none'), 
				('17', '6', 'br'), 
				('18', '6', 'xhtml')";

## ----------------------------
##  Records of exp_fieldtypes
## ----------------------------

	$sql[] = "	INSERT INTO exp_fieldtypes
					(name, version, settings, has_global_settings) 
			 	VALUES 
					('brilliant_retail', '1.0.0', 'YTowOnt9', 'n')";

## exp_channel_titles

	/*
	$sql[] = "INSERT INTO exp_channel_titles VALUES 
				('1', '1', '1', '1', '0', '0', '127.0.0.1', 'About', 'about', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288630825', 'n', '2010', '11', '01', '0', '0', '20101114152226', '0', '0'), 
				('2', '1', '1', '1', '0', '0', '127.0.0.1', 'Site Map', 'site_map', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288609217', 'n', '2010', '11', '01', '0', '0', '20101112224118', '0', '0'), 
				('3', '1', '1', '1', '0', '0', '127.0.0.1', 'Privacy Policy', 'privacy_policy', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288605656', 'n', '2010', '11', '01', '0', '0', '20101114142357', '0', '0'), 
				('4', '1', '1', '1', '0', '0', '127.0.0.1', 'Terms of Service', 'terms_of_service', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288605627', 'n', '2010', '11', '01', '0', '0', '20101114142328', '0', '0'), 
				('6', '1', '2', '1', '0', '0', '127.0.0.1', 'The Best Way to Run a Business', 'the_best_way_to_run_a_business', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '11', '0', '0', '20101101164848', '0', '0'), 
				('7', '1', '2', '1', '0', '0', '127.0.0.1', 'Ways to Avoid Working Long Hours', 'ways_to_avoid_working_long_hours', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '0', '0'), 
				('8', '1', '2', '1', '0', '0', '127.0.0.1', 'Best Products of All Time', 'best_products_of_all_time', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '0', '0'), 
				('9', '1', '2', '1', '0', '0', '127.0.0.1', 'Tips for Communicating with Customers', 'tips_for_communicating_with_customers', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '0', '0'), 
				('10', '1', '2', '1', '0', '0', '127.0.0.1', 'New Internet Marketing Ideas for E-commerce', 'new_internet_marketing_ideas_for_e_commerce', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '0', '0'), 
				('11', '1', '2', '1', '0', '0', '127.0.0.1', 'Happy Clients Tell Their Stories', 'happy_clients_tell_their_stories', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '0', '0'), 
				('12', '1', '2', '1', '0', '0', '127.0.0.1', 'Business That Would Work Better Online', 'business_that_would_work_better_online', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '0', '0'), 
				('13', '1', '2', '1', '0', '0', '127.0.0.1', 'Different Approaches to Managing Inventory', 'different_approaches_to_managing_inventory', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '0', '0'), 
				('14', '1', '2', '1', '0', '0', '127.0.0.1', 'Service Businesses That Are Booming', 'service_businesses_that_are_booming', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '0', '0'), 
				('15', '1', '2', '1', '0', '0', '127.0.0.1', 'Companies Reinventing the Retail Business', 'companies_reinventing_the_retail_business', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1288602047', 'n', '2010', '11', '10', '0', '0', '20101101164848', '1289768786', '2'), 
				('16', '1', '2', '1', '0', '0', '127.0.0.1', 'Post with Products', 'post_with_products', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1289630905', 'n', '2010', '11', '12', '0', '0', '20101115170526', '0', '3'), 
				('17', '1', '3', '1', '0', '0', '127.0.0.1', 'Home Page', 'home_page', 'open', 'y', '0', '0', '0', '0', 'y', 'n', '1289774045', 'n', '2010', '11', '14', '0', '0', '20101114150606', '0', '0')";
	*/
	
## exp_channels

	$sql[] = "INSERT INTO exp_channels VALUES 
				('1', '1', 'content', 'General Content', '".$this->userdata['site_url']."/index.php', '', 'en', '4', '0', '0', '0', '', '1', 'open', '1', null, '', 'y', 'y', null, 'all', 'y', 'y', 'n', '', '', 'y', 'n', 'n', 'n', '5000', '0', 'y', 'xhtml', 'safe', 'n', 'y', 'n', 'n', '', '0', '', '', 'y', '', 'y', '100', '', '', '0'), 
				('2', '1', 'blog', 'Blog', '".$this->userdata['site_url']."/index.php', '', 'en', '11', '5', '0', '1289768786', '1', '1', 'open', '2', null, '', 'y', 'y', null, 'all', 'y', 'y', 'n', '', '', 'y', 'n', 'n', 'n', '5000', '0', 'y', 'xhtml', 'safe', 'n', 'y', 'n', 'n', '', '0', '', '', 'y', '', 'n', '10', '', '', '0'), 
				('3', '1', 'home', 'Home Page', '".$this->userdata['site_url']."/index.php', null, 'en', '1', '0', '0', '0', null, '1', 'open', '3', null, null, 'y', 'y', null, 'all', 'y', 'y', 'n', null, null, 'y', 'n', 'n', 'n', '5000', '0', 'y', 'xhtml', 'safe', 'n', 'y', 'n', 'n', null, '0', null, null, 'y', null, 'n', '10', '', '', '0')";
	
## exp_category_posts

	$sql[] = "INSERT INTO exp_category_posts VALUES ('6', '5'), 
	('7', '5'), 
	('8', '6'), 
	('9', '5'), 
	('10', '6'), 
	('11', '5'), 
	('12', '5'), 
	('13', '6'), 
	('14', '5'), 
	('15', '5');";

## exp_category_groups

	$sql[] = "INSERT INTO exp_category_groups 
				(group_id,site_id,group_name,sort_order,field_html_formatting,can_edit_categories,can_delete_categories) 
				VALUES 
				('1', '1', 'Blog Categories', 'c', 'all', '', '');";

## exp_category_field_data

	$sql[] = "INSERT INTO exp_category_field_data VALUES ('6', '1', '1'), 
	('5', '1', '1'), 
	('7', '1', '1');";

## exp_categories

	$sql[] = "INSERT INTO exp_categories VALUES ('6', '1', '1', '0', 'Product', 'product', '', '', '2'), 
	('5', '1', '1', '0', 'Company', 'company', '', '', '1'), 
	('7', '1', '1', '0', 'Archive', 'archive', '', '', '3');";

## exp_upload_prefs
	
	$media_dir = realpath(FCPATH.'../media/images');  
	$media_dir = rtrim($media_dir,'/').'/';
	chmod($media_dir,DIR_WRITE_MODE);
	$sql[] = "INSERT INTO exp_upload_prefs 
				(id,
				site_id,
				name,
				server_path,
				url,
				allowed_types,
				max_size,
				max_height,
				max_width,
				properties,
				pre_format,
				post_format, 
				file_properties,
				file_pre_format,
				file_post_format)
				
					VALUES 
				
				('1', '1', 'BR Images', '".$media_dir."', '/media/images/', 'img', '', '', '', 'style=\"border: 0;\" alt=\"image\"', '', '', '', '', '');";

foreach ($sql as $row){
	$this->db->query($row);
}

// Set strict 404 settings
$this->config->update_site_prefs(array(
										'member_theme'	=> 'brilliant_retail',
										'strict_urls'	=> 'y',
										'site_404'		=> '_assets/404'
										),
										1 // site id
								);